[phases.setup]
nixPkgs = ["python310", "postgresql", "gcc"]

[phases.install]
cmds = ["pip install -r requirements.txt", "pip install gunicorn psycopg2-binary"]

[phases.build]
cmds = ["python manage.py collectstatic --noinput"]

[start]
cmd = "python manage.py migrate && gunicorn backend.wsgi:application --bind 0.0.0.0:$PORT"
